### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by Nadeem1337** [yonjah/node_acl_sequelize#11]
when i am trying to run   acl.allow('guest', 'blogs', 'view');
it gives me the following error 
Unhandled rejection TypeError: Cannot read property 'reduce' of undefined
 at SequelizeBackend.sbEnd [as end] (E:\xampp\htdocs\echallan\node_modules\acl-sequelize\lib\backend.js:121:23)

**Comment by yonjah** [comment]
Did you properly installed all your packages.
the line calls to `Promise.reduce` so the only way I can think of for `Promise` to be undefined is if bluebird is not properly installed

**Comment by Nadeem1337** [comment]
Yes, i believe all the packages are properly installed without any error.
In fact install it twice.

**Comment by yonjah** [comment]
Which version of node, sequelize and bluebird do you have.
You can try inspect the `node_modules\acl-sequelize\lib\backend.js` file and to see why bluebird is not loading properly.

Is there any reason why you running this in a windows / xamp environment ?

**Comment by Nadeem1337** [comment]
Node : 11.11.0
sequelize: "^5.0.0-beta.11"
"bluebird": "^3.5.3"
it is my company machine and they expect us to run windows

**Comment by yonjah** [comment]
Try to use Sequelize 4 instead of 5

**Comment by BigGillyStyle** [comment]
https://github.com/yonjah/node_acl_sequelize/pull/12

If you need to use Sequelize v5, for now I've published a scoped version of this package that is v5-compatible but is not compatible for v4 and earlier: https://www.npmjs.com/package/@biggillystyle/acl-sequelize

**Comment by yonjah** [comment]
@BigGillyStyle This is a bit uncommon to republish an existing package to npm and can be misleading to users.
Do you consider making the suggested changes to #12 ?

**Comment by yonjah** [comment]
@BigGillyStyle I published a new version that supports Sequelize v5 (without breaking support to old versions or introducing any breaking changes). 
I'm not sure if it's possible but I would suggest removing or at least deprecating the npm fork to prevent any confusion regarding this package and it's API

**Comment by BigGillyStyle** [comment]
@yonjah Sorry about the trouble and confusion I caused.  I definitely don't want to maintain a fork, so I've gone ahead and unpublished my version and put a note on my repo.

**Comment by sandeep-6698** [comment]
Same error with these versions

node: "v12.18.3",
"sequelize": "^6.3.5",
"acl": "^0.4.11",
"acl-sequelize": "^0.3.5"

**Comment by sameh-khemira** [comment]
facing the same problem with :
"sequelize": "6.21.6",
"acl-sequelize": "0.3.5",
"bluebird": "3.7.2",
