### ISSUE TITLE
Always executes over default transaction

### ISSUE THREAD

**Issue by igordeoliveirasa** [yonjah/node_acl_sequelize#27]
I need acl methods run over my began transaction not over default transactions.. how could I do?

**Comment by yonjah** [comment]
I don't think acl API will support anyway for you to pass the transaction

Your only bet might be to try and use CLS -
http://docs.sequelizejs.com/manual/transactions.html

Sequelize has a few issues handling transactions so make sure you use a recent version (and even than your mileage may vary)

**Comment by igordeoliveirasa** [comment]
@yonjah anyway, node_acl_sequelize is not respecting my began transactions..

**Comment by yonjah** [comment]
@igordeoliveirasa CLS works on the Promise chain that created the transaction
It won't collide between two users.
Since node_acl API will not allow for extra parameters I don't think there is any other option that will work
