### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ralvescosta** [yonjah/node_acl_sequelize#29]
Hi guys.

Please, if there is a little more detailed documentation on how to use migration and how to integrate acl into models, make it available. 

Thank you very much.

**Comment by yonjah** [comment]
Hi @ralvescosta 
Not sure what you mean by migrations, but this module is just a port for [node_acl](https://github.com/OptimalBits/node_acl) to use Sequelize as backend

You can check `node_acl` documentation to see how to use it.
Just keep in mind that `node_acl` hasn't been updated in a while so you might want to check other options (not sure what else is available).
