### ISSUE TITLE
Too Many Connections

### ISSUE THREAD

**Issue by ericuldall** [yonjah/node_acl_sequelize#3]
I'm having an issue with this sequelize connector and acl. It was working well for sometime, now all of the sudden i'm getting constant errors:

```
{ [Error: ER_CON_COUNT_ERROR: Too many connections]
  code: 'ER_CON_COUNT_ERROR',
  errno: 1040,
  sqlState: '08004',
  fatal: true }
```

Is this a known issue? Any possible fix?

**Comment by ericuldall** [comment]
UPDATE: I believe that sequelize is not properly handling clean up of connections, which is causing connections to pile up.  The problem is, MySQL default wait_timeout, is 8 hours (28800 seconds). So this can create quite the back log of inactive connections. I've temporarily changed my wait_timeout to 60 seconds, which seems to be alleviating, the problem, though i'd hardly consider it a solution.

**Comment by yonjah** [comment]
@ericuldall  which version of `Sequelize` your using ? 
version 3 had major api changes and with the new way npm handles dependencies you might be 
using a different version then the one I've tested this library with.

With that in mind note that this package some issues I didn't have time to attend yet so I wouldn't use it on anything too important

**Comment by ericuldall** [comment]
I'm currently using v3.13.0

**Comment by yonjah** [comment]
I'm surprised its even working at all since there were major api changes in Sequelize 3
and currently it was only tested on version 2
I'll try to see if I have time to upgrade Sequelize but it might take some time

**Comment by kahwooi** [comment]
Is this problem solve yet?

**Comment by yonjah** [comment]
Not yet.
I want to do some major changes to the code so it might take some time

**Comment by maenu** [comment]
@yonjah I am not sure if I understand you correctly: Do you mean this project should not be used at all with Sequelize 3? I just ran the tests with Sequelize 3.21.0 and they all passed, as #1 stated too. Coverage seems not to bad either. So far, I have no experience with this project, but I intend to use it together with Sequelize 3, I'll come back if I notice any problems.

**Comment by yonjah** [comment]
@maenu I can't be sure if this issue is actually related to `Sequelize` version or some general bug in `acl-sequelize` or even with the specific OP implementation.
I didn't look into it deeply.

I would suggest not using `acl-sequelize` in production.
I wrote this package mostly to see if `acl` package would suite my needs and in the end decided to roll a custom implementation. so unrelated to this issue the implementation is very basic.
I hope I'll have the time to do some major rewrite but I'm not sure when I'll be able to do so

**Comment by yonjah** [comment]
Closing this issue as it is probably resolved, feel free to reopen if you are still affected by it
