### ISSUE TITLE
this module is not respecting the table schema for creating the acl tables

### ISSUE THREAD

**Issue by shemna** [yonjah/node_acl_sequelize#6]
I supposed that the following code should create the acl tables in  'test' schema, instead generated in public schema
var Acl       = require('acl');
var Sequelize = require('sequelize');
var AclSeq    = require('acl-sequelize');
var db        = new Sequelize( 'acl', 'postgres', 'postgres', {
            schema: 'test',
            dialectOptions: {
                searchPath: 'test',
                prependSearchPath: true
            },
            host: 'localhost',
            port: 5432,
            dialect: 'postgres'
        });

var abc_acl       = new Acl(new AclSeq(db, { prefix: 'acl_' }));

I dig bit mmore on teh code, an i see that line 30 of lib/dbTasks.js should be passed with db.options.

here is the modified line
db.define(name, schema[table] || defaultSchema, db.options).sync();

**Comment by yonjah** [comment]
I don't have experience with Postgres but from sequelize docs ->
http://docs.sequelizejs.com/en/latest/api/sequelize/#definemodelname-attributes-options-model
The options passed to the `define` method are any merged with `options.defined` passed to the constructor so if I undestand what you are trying to do you need to call the constructor like this

```javascript
    var db = new Sequelize( 'acl', 'postgres', 'postgres', {
        schema: 'test',
        define: {
            schema: 'test'
        },
        dialectOptions: {
            searchPath: 'test',
            prependSearchPath: true
        },
        host: 'localhost',
        port: 5432,
        dialect: 'postgres'
    });
```

**Comment by shemna** [comment]
Thanks alot. Thant worked
