### ISSUE TITLE
String operator aliases are deprecated in Sequelize (4.12+)

### ISSUE THREAD

**Issue by deksden** [yonjah/node_acl_sequelize#7]
Recent Sequelize (4.12.0+) deprecate usage of string aliases like $or / $in. Now its safer to use [Op.or] from Sequelize.Op. See readme for changes. So, some code need to be changed.

**Comment by yonjah** [comment]
Merged changes to v0.2.0

**Comment by deksden** [comment]
I can confirm that 0.2.0 works as expected and solves issue! My project's tests are fine
